TaskType = "Search"

[SearchParameters]
DisposeOfFileWhenDone = true
DoParsimony = true
ModPeptidesAreDifferent = false
NoOneHitWonders = false
MatchBetweenRuns = false
MbrFdrThreshold = 0.01
Normalize = false
QuantifyPpmTol = 5.0
DoHistogramAnalysis = false
SearchTarget = true
DecoyType = "Reverse"
MassDiffAcceptorType = "OneMM"
WritePrunedDatabase = false
KeepAllUniprotMods = true
DoLocalizationAnalysis = false
DoLabelFreeQuantification = false
UseSharedPeptidesForLFQ = false
DoMultiplexQuantification = false
MultiplexModId = "TMT10"
DoSpectralRecovery = false
SearchType = "Classic"
LocalFdrCategories = ["FullySpecific"]
MaxFragmentSize = 30000.0
MinAllowedInternalFragmentLength = 0
HistogramBinTolInDaltons = 0.003
MaximumMassThatFragmentIonScoreIsDoubled = 0.0
WriteMzId = true
WritePepXml = false
WriteHighQValuePsms = true
WriteDecoys = true
WriteContaminants = true
WriteIndividualFiles = true
WriteSpectralLibrary = false
UpdateSpectralLibrary = false
CompressIndividualFiles = false
TCAmbiguity = "RemoveContaminant"
IncludeModMotifInMzid = false
WriteDigestionProductCountFile = false

[SearchParameters.ModsToWriteSelection]
'N-linked glycosylation' = 3
'O-linked glycosylation' = 3
'Other glycosylation' = 3
'Common Biological' = 3
'Less Common' = 3
Metal = 3
'2+ nucleotide substitution' = 3
'1 nucleotide substitution' = 3
UniProt = 2

[CommonParameters]
TaskDescriptor = "SearchTask"
MaxThreadsToUsePerFile = 15
ListOfModsFixed = ""
ListOfModsVariable = ""
DoPrecursorDeconvolution = true
UseProvidedPrecursorInfo = false
DeconvolutionMaxAssumedChargeState = 60
TotalPartitions = 1
ProductMassTolerance = "±20.0000 PPM"
PrecursorMassTolerance = "±10.0000 PPM"
AddCompIons = false
QValueThreshold = 0.01
PepQValueThreshold = 1.0
ScoreCutoff = 5.0
QValueCutoffForPepCalculation = 0.005
ReportAllAmbiguity = true
NumberOfPeaksToKeepPerWindow = 200
MinimumAllowedIntensityRatioToBasePeak = 0.01
NormalizePeaksAccrossAllWindows = false
TrimMs1Peaks = false
TrimMsMsPeaks = false
CustomIons = []
AssumeOrphanPeaksAreZ1Fragments = false
MaxHeterozygousVariants = 4
MinVariantDepth = 1
AddTruncations = false
DissociationType = "HCD"
SeparationType = "HPLC"
MS2ChildScanDissociationType = "Unknown"
MS3ChildScanDissociationType = "Unknown"
UseMostAbundantPrecursorIntensity = true

[CommonParameters.PrecursorDeconvolutionParameters]
DeconvolutionType = "IsoDecDeconvolution"
PhaseRes = 8
CssThreshold = 0.699999988079071
MatchTolerance = 5.0
MaxShift = 3
MzWindow = [-1.04999995231628, 2.04999995231628]
KnockdownRounds = 5
MinAreaCovered = 0.200000002980232
DataThreshold = 0.0500000007450581
ReportMulitpleMonoisos = false
AdductMass = 1.00727272033691
MinAssumedChargeState = 1
MaxAssumedChargeState = 60
Polarity = "Positive"

[CommonParameters.ProductDeconvolutionParameters]
DeconvolutionType = "ClassicDeconvolution"
MinAssumedChargeState = 1
MaxAssumedChargeState = 8
Polarity = "Positive"

[CommonParameters.DigestionParams]
InitiatorMethionineBehavior = "Variable"
MaxMissedCleavages = 2
MaxModificationIsoforms = 4096
SearchModeType = "Full"
FragmentationTerminus = "Both"
SpecificProtease = "top-down"
GeneratehUnlabeledProteinsForSilac = true
KeepNGlycopeptide = false
KeepOGlycopeptide = false
Protease = "top-down"
MinPeptideLength = 7
MaxPeptideLength = 2147483647
MaxModsForPeptide = 2

[[FileSpecificParameters]]
[[FileSpecificParameters]]
[[FileSpecificParameters]]
[[FileSpecificParameters]]
[[FileSpecificParameters]]
